### ISSUE TITLE
JSONpimp problem with gha

### ISSUE THREAD

**Issue by skrobi12** [Teaching-projects/-SZE-MOSZE-2020-AMD_Bike#14]
@hegyhati @oliverosz Egy olyan problémánk van a JSONpimp-el, hogy megcsináltuk, és bár lokálisan lefut, valahogy gha-n mintha végtelen ciklusba lépne annál a résznél, ahol futtatni akarjuk a scenario1.json-t.
![JSONpimp](https://user-images.githubusercontent.com/57217622/98959089-3c326f80-2503-11eb-90f4-164cdd1349d0.png)

**Comment by oliverosz** [comment]
Lokálisan biztos jó branchen futtattad? Nekem lokálisan indítva is végtelen ciklusba kerül, ugyanúgy, mint GHA-n. Valami nem jó a megoldásban. Debuggoljátok ki.

**Comment by skrobi12** [comment]
@oliverosz Hát most le clone-oztam ujra a mastert, switch-eltem a Jsonpimp branch-re, és le pull-oltam azt, de a "make sca-test"-el nekem működik. Vagy nem így kéne megnézni?

**Comment by oliverosz** [comment]
@skrobi12 Az érdekes, én is ezt csináltam és nálam cégtelen ciklus... De most belenéztem a kódba, és tényleg hibás. A lista utolsó eleme után rosszul kezeli a lista végének ellenőrzését.

**Comment by skrobi12** [comment]
Jólvan ránézünk, aztán legfeljebb gha-n tesztelünk, nem lokálisan.

**Comment by skrobi12** [comment]
@oliverosz Sikerült megoldani, bár még mindig nem tudjuk, hogy miért működöttt nálunk lokálisan. Köszönjük szépen a segítséget, és a gyors válaszokat. :)

**Comment by hegyhati** [comment]
ORulok, hogy megoldodott. Cancelled dologgal en ugy talalkoztam, hogyha van tobb job, es mar tuti, hogy valami mas elhasal, akkor alapertelmezettena  folyamatban levoket kinyomja, mert mar igyis-ugyis mindegy, elhasal. De itt ha jol latom, nem errol volt szo.
