### ISSUE TITLE
Team hozzárendelés JsonPimp-hez

### ISSUE THREAD

**Issue by Szabi1104** [Teaching-projects/-SZE-MOSZE-2020-AMD_Bike#15]
@hegyhati Szeretnénk kérni @Teaching-projects/mortar_kombat csapat hozzárendelését a repónkhoz a JsonPimp-es feladatbeli review-ok elvégzéséhez, mert az előző társcsapatunk már Closed lett és ezt a feladatot ők már nem csinálják.
Köszönjük!

**Comment by hegyhati** [comment]
done. Amugy a review-bol is tanulhat a closed csapat is.
