### ISSUE TITLE
Final report

### ISSUE THREAD

**Issue by Szabi1104** [Teaching-projects/-SZE-MOSZE-2020-AMD_Bike#25]
@hegyhati Elkészülünk a legvégső kóddal is, valamint a Report.md is ki lett töltve és a két videó is el lett készítve. 😄  Egyetlen apró dolog csupán: a Report-ban a rendering feladat merge dátumát véletlenül elfelejtettük beírni. Időhiány miatt azt végül magunknak review-oltuk és 12.09-én bemergeltük, hogy szépen ott legyen a masteren, csupán a Report-ban maradt le tehát a dátum.

**Comment by hegyhati** [comment]
Semmi sem tart vissza benneteket abban, hogy beleirjatok :-) Ranezni ugyis holnap fogok legkorabban, mara meg van boven mas.

**Comment by Szabi1104** [comment]
@hegyhati Teljesen igazad van, szépen bele is írtuk. Így tehát ténylegesen minden rendben van 😄

**Comment by Szabi1104** [comment]
@hegyhati Egy egészen apróság csupán amit most vettünk észre, hogy a Readme leírásában a csapattagokhoz egy kis kavarodás meg viccelődés miatt "Boja Richard" került helyettem :sweat_smile: A csapatunk tagjai helyesen tehát: Hajdu Norbert, Skrapits Róbert Ágoston és én, Gergály Szabolcs. A Report-ban azonban mindez legalább jól szerepel, bocsi ezért a pici malőrért! :sweat_smile:

**Comment by Szabi1104** [comment]
@hegyhati Csupán a biztonság kedvéért betagellek újra, mert mi még nem kaptunk értékelést tőletek. Bocsi ha épp haladtok sorban és még mi is hátra vagyunk, csak ha esetleg kimaradtunk volna, abból kifolyólag taggeltelek újra. Előra is köszönjük ha majd ránézel a munkánkra! :smile:

**Comment by hegyhati** [comment]
Hm... valoban kimaradtatok valahogy. Sorry, nezem.

**Comment by hegyhati** [comment]
![image](https://user-images.githubusercontent.com/13832329/102013019-be55c400-3d4d-11eb-89a0-aa37ebd37426.png)

**Comment by hegyhati** [comment]
Na, a masodik videot kicist felreertettetek, itt nem konkretan az erdekelt volna, hogy a program minden hibat lekezel, hanem hogy azokkal a cuccokkal menozzetek, amiket felev kozben tanultatok, hogy nincs memory leak, mert letesztelitek minden commit utan, stb. 

Node rendben van, szep munka, jar az otos mindenkinek, Szabolcs jon egy lada sorrel a ket masik tagnak, amiert kihagyta a meetingeket. A Rickroll miatt meg... jottok ti meg az en utcamba :smiling_imp:
