### ISSUE TITLE
Missing "settings" tab

### ISSUE THREAD

**Issue by hajdunorbi** [Teaching-projects/-SZE-MOSZE-2020-AMD_Bike#7]
Nem férek hozzá a settings-hez, ami szükséges lenne a doxygen-es feladatnál.

**Comment by hegyhati** [comment]
csak 4 nap kesesetek van, es megcsak le sem irtatok, hogy mit szeretnetek, hogy beallitsak... beallitottam a github hostingot a gh-pages/root-ra.

**Comment by hajdunorbi** [comment]
Köszönöm szépen és elnézést a kellemetlenségért, azt gondoltam ezt magamnak kell beállítani.

**Comment by hegyhati** [comment]
Azzal semmi baj, csak mult het pentekig ra kellett volna jonni, hogy magandak nem megy :-)
